// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"time"
)

type Expense struct {
	ID          int32
	Description string
	Amount      string
	CreatedAt   time.Time
}
